language: node_js
node_js:
  - 4
  - 5

install:
  - npm install
  - pushd example && npm install && popd

script:
  - node --version && npm --version
  - npm test
  - pushd example && node build.js && popd

after_success:
  - npm run codeclimate

###

addons:
  code_climate:
    repo_token:
      secure: HXQ374aa+NZRavvxaUEV+txh+kH/ZRPa1PmE4f3cVlv0KkyaHaf9rFc3ivu8hUvbWHgbysACH/pGJPM4C9DQII/lTr8r6Hn8JBri3J6Slj1y7bHbM0y/xOi1CBgjp13f8clLhBhvZQ+2GpGXI/yUzpcIheEWPj8BbgI8M6aJWWk=

git:
  depth: 10

matrix:
  fast_finish: true

sudo: false
